#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : grilo-plugins
Version  : 0.3.8
Release  : 11
URL      : https://download.gnome.org/sources/grilo-plugins/0.3/grilo-plugins-0.3.8.tar.xz
Source0  : https://download.gnome.org/sources/grilo-plugins/0.3/grilo-plugins-0.3.8.tar.xz
Summary  : Plugins for the Grilo Framework
Group    : Development/Tools
License  : LGPL-2.1
Requires: grilo-plugins-lib
Requires: grilo-plugins-license
Requires: grilo-plugins-locales
Requires: grilo-plugins-data
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gmime-dev
BuildRequires : gperf
BuildRequires : json-glib-dev
BuildRequires : libarchive-dev
BuildRequires : lua-dev
BuildRequires : pkgconfig(grilo-0.3)
BuildRequires : sqlite-autoconf-dev

%description
Thanks for using Grilo!
=== What is Grilo? ===
Grilo is a framework for browsing and searching media content from various
sources using a single API.

%package data
Summary: data components for the grilo-plugins package.
Group: Data

%description data
data components for the grilo-plugins package.


%package dev
Summary: dev components for the grilo-plugins package.
Group: Development
Requires: grilo-plugins-lib = %{version}-%{release}
Requires: grilo-plugins-data = %{version}-%{release}
Provides: grilo-plugins-devel = %{version}-%{release}

%description dev
dev components for the grilo-plugins package.


%package doc
Summary: doc components for the grilo-plugins package.
Group: Documentation

%description doc
doc components for the grilo-plugins package.


%package lib
Summary: lib components for the grilo-plugins package.
Group: Libraries
Requires: grilo-plugins-data = %{version}-%{release}
Requires: grilo-plugins-license = %{version}-%{release}

%description lib
lib components for the grilo-plugins package.


%package license
Summary: license components for the grilo-plugins package.
Group: Default

%description license
license components for the grilo-plugins package.


%package locales
Summary: locales components for the grilo-plugins package.
Group: Default

%description locales
locales components for the grilo-plugins package.


%prep
%setup -q -n grilo-plugins-0.3.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537811278
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/doc/grilo-plugins
cp COPYING %{buildroot}/usr/share/doc/grilo-plugins/COPYING
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang grilo-plugins

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/grilo-plugins/grl-lua-factory/grl-acoustid.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-appletrailers.gresource
/usr/share/grilo-plugins/grl-lua-factory/grl-appletrailers.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-euronews.gresource
/usr/share/grilo-plugins/grl-lua-factory/grl-euronews.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-guardianvideos.gresource
/usr/share/grilo-plugins/grl-lua-factory/grl-guardianvideos.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-itunes-podcast.gresource
/usr/share/grilo-plugins/grl-lua-factory/grl-itunes-podcast.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-lastfm-cover.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-metrolyrics.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-musicbrainz.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-pocket.gresource
/usr/share/grilo-plugins/grl-lua-factory/grl-pocket.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-radiofrance.gresource
/usr/share/grilo-plugins/grl-lua-factory/grl-radiofrance.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-spotify-cover.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-theaudiodb-cover.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-thegamesdb.lua
/usr/share/grilo-plugins/grl-lua-factory/grl-video-title-parsing.lua

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/grilo-plugins-0.3.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/examples/example-tmdb.c
/usr/share/help/C/grilo-plugins/grilo-plugins.xml
/usr/share/help/C/grilo-plugins/legal.xml
/usr/share/help/cs/examples/example-tmdb.c
/usr/share/help/cs/grilo-plugins/grilo-plugins.xml
/usr/share/help/cs/grilo-plugins/legal.xml
/usr/share/help/de/examples/example-tmdb.c
/usr/share/help/de/grilo-plugins/grilo-plugins.xml
/usr/share/help/de/grilo-plugins/legal.xml
/usr/share/help/es/examples/example-tmdb.c
/usr/share/help/es/grilo-plugins/grilo-plugins.xml
/usr/share/help/es/grilo-plugins/legal.xml
/usr/share/help/pl/examples/example-tmdb.c
/usr/share/help/pl/grilo-plugins/grilo-plugins.xml
/usr/share/help/pl/grilo-plugins/legal.xml
/usr/share/help/pt_BR/examples/example-tmdb.c
/usr/share/help/pt_BR/grilo-plugins/grilo-plugins.xml
/usr/share/help/pt_BR/grilo-plugins/legal.xml
/usr/share/help/sv/examples/example-tmdb.c
/usr/share/help/sv/grilo-plugins/grilo-plugins.xml
/usr/share/help/sv/grilo-plugins/legal.xml

%files lib
%defattr(-,root,root,-)
/usr/lib64/grilo-0.3/libgrlfilesystem.so
/usr/lib64/grilo-0.3/libgrlgravatar.so
/usr/lib64/grilo-0.3/libgrljamendo.so
/usr/lib64/grilo-0.3/libgrlluafactory.so
/usr/lib64/grilo-0.3/libgrlmagnatune.so
/usr/lib64/grilo-0.3/libgrlmetadatastore.so
/usr/lib64/grilo-0.3/libgrlraitv.so
/usr/lib64/grilo-0.3/libgrlshoutcast.so

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/grilo-plugins/COPYING

%files locales -f grilo-plugins.lang
%defattr(-,root,root,-)

